

def get_CIAWFB_group_list():
    return ('Introduction',
            'Geography',
            'People and Society',
            'Government',
            'Economy',
            'Energy',
            'Communications',
            'Transportation',
            'Military',
            'Transnational Issues')


def get_CIAWFB_grouped_fields():
    groups = get_CIAWFB_group_list()
    return {groups[0]: ('background',),
            groups[1]: ('location',
                        'geographic_coordinates',
                        'map_references',
                        'area',
                        'area_comparative',
                        'land_boundaries',
                        'coastline',
                        'maritime_claims',
                        'climate',
                        'terrain',
                        'elevation_extremes',
                        'natural_resources',
                        'land_use',
                        'irrigated_land',
                        'total_renewable_water_resources',
                        'freshwater_withdrawal_domesticindustrialagricultural',
                        'natural_hazards',
                        'environment_current_issues',
                        'environment_international_agreements',
                        'geography_note'),
            groups[2]: ('nationality',
                        'ethnic_groups',
                        'languages',
                        'religions',
                        'demographic_profile',
                        'population',
                        'age_structure',
                        'median_age',
                        'population_growth_rate',
                        'birth_rate',
                        'death_rate',
                        'net_migration_rate',
                        'urbanization',
                        'major_cities_population',
                        'sex_ratio',
                        'maternal_mortality_rate',
                        'infant_mortality_rate',
                        'life_expectancy_at_birth',
                        'total_fertility_rate',
                        'health_expenditures',
                        'physicians_density',
                        'hospital_bed_density',
                        'drinking_water_source',
                        'sanitation_facility_access',
                        'hivaids_adult_prevalence_rate',
                        'hivaids_people_living_with_hivaids',
                        'hivaids_deaths',
                        'major_infectious_diseases',
                        'obesity_adult_prevalence_rate',
                        'children_under_the_age_of_5_years_underweight',
                        'education_expenditures',
                        'literacy',
                        'school_life_expectancy_primary_to_tertiary_education',
                        'unemployment_youth_ages_15_24',
                        'people_note'),
            groups[3]: ('country_name',
                        'dependency_status',
                        'government_type',
                        'capital',
                        'administrative_divisions',
                        'dependent_areas',
                        'independence',
                        'national_holiday',
                        'constitution',
                        'legal_system',
                        'international_law_organization_participation',
                        'suffrage',
                        'executive_branch',
                        'legislative_branch',
                        'judicial_branch',
                        'political_parties_and_leaders',
                        'political_pressure_groups_and_leaders',
                        'international_organization_participation',
                        'diplomatic_representation_in_the_us',
                        'diplomatic_representation_from_the_us',
                        'flag_description',
                        'national_symbols',
                        'national_anthem',
                        'government_note'),
            groups[4]: ('economy_overview',
                        'gdp_purchasing_power_parity',
                        'gdp_official_exchange_rate',
                        'gdp_real_growth_rate',
                        'gdp_per_capita_ppp',
                        'gdp_composition_by_sector',
                        'labor_force',
                        'labor_force_by_occupation',
                        'unemployment_rate',
                        'population_below_poverty_line',
                        'household_income_or_consumption_by_percentage_share',
                        'distribution_of_family_income_gini_index',
                        'investment_gross_fixed',
                        'budget',
                        'taxes_and_other_revenues',
                        'budget_surplus_or_deficit',
                        'public_debt',
                        'inflation_rate_consumer_prices',
                        'central_bank_discount_rate',
                        'commercial_bank_prime_lending_rate',
                        'stock_of_narrow_money',
                        'stock_of_broad_money',
                        'stock_of_domestic_credit',
                        'market_value_of_publicly_traded_shares',
                        'agriculture_products',
                        'industries',
                        'industrial_production_growth_rate',
                        'current_account_balance',
                        'exports',
                        'exports_commodities',
                        'exports_partners',
                        'imports',
                        'imports_commodities',
                        'imports_partners',
                        'reserves_of_foreign_exchange_and_gold',
                        'debt_external',
                        'stock_of_direct_foreign_investment_at_home',
                        'stock_of_direct_foreign_investment_abroad',
                        'exchange_rates',
                        'fiscal_year'),
            groups[5]: ('electricity_production',
                        'electricity_consumption',
                        'electricity_exports',
                        'electricity_imports',
                        'electricity_installed_generating_capacity',
                        'electricity_from_fossil_fuels',
                        'electricity_from_nuclear_fuels',
                        'electricity_from_hydroelectric_plants',
                        'electricity_from_other_renewable_sources',
                        'crude_oil_production',
                        'crude_oil_exports',
                        'crude_oil_imports',
                        'crude_oil_proved_reserves',
                        'refined_petroleum_products_production',
                        'refined_petroleum_products_consumption',
                        'refined_petroleum_products_exports',
                        'refined_petroleum_products_imports',
                        'natural_gas_production',
                        'natural_gas_consumption',
                        'natural_gas_exports',
                        'natural_gas_imports',
                        'natural_gas_proved_reserves',
                        'carbon_dioxide_emissions_from_consumption_of_energy'),
            groups[6]: ('telephones_main_lines_in_use',
                        'telephones_mobile_cellular',
                        'telephone_system',
                        'broadcast_media',
                        'internet_country_code',
                        'internet_hosts',
                        'internet_users',
                        'communications_note'),
            groups[7]: ('airports',
                        'airports_with_paved_runways',
                        'airports_with_unpaved_runways',
                        'heliports',
                        'pipelines',
                        'railways',
                        'roadways',
                        'waterways',
                        'merchant_marine',
                        'ports_and_terminals',
                        'transportation_note'),
            groups[8]: ('military_branches',
                        'military_service_age_and_obligation',
                        'manpower_available_for_military_service',
                        'manpower_fit_for_military_service',
                        'manpower_reaching_militarily_significant_age_annually',
                        'military_expenditures',
                        'military_note'),
            groups[9]: ('disputes_international',
                        'refugees_and_internally_displaced_persons',
                        'trafficking_in_persons',
                        'illicit_drugs'),
            }
