from django.db import models


class Country(models.Model):
    def __unicode__(self):
        return self.CIAWFB_name_short
    # We use the CIA World Factbook "conventional short form" of the country name
    # as our canonical source for country names. The url_name is the slugified version of that.
    url_name = models.CharField(max_length=100)
    CIAWFB_name_short = models.CharField(max_length=100)


class CIAWFBFieldInfo(models.Model):
    def __unicode__(self):
        return "%s" % (self.field_name)
    field_dbname = models.CharField(max_length=100)
    field_name = models.CharField(max_length=100)
    field_description = models.CharField(max_length=20000)


class CIAWFBEntry(models.Model):
    def __unicode__(self):
        return "%s (%s)" % (self.country, self.date_entered)

    country = models.ForeignKey(Country)
    date_entered = models.DateField()

    administrative_divisions = models.CharField(max_length=3600, blank=True, null=True)
    age_structure = models.CharField(max_length=350, blank=True, null=True)
    agriculture_products = models.CharField(max_length=300, blank=True, null=True)
    airports = models.CharField(max_length=800, blank=True, null=True)
    airports_with_paved_runways = models.CharField(max_length=200, blank=True, null=True)
    airports_with_unpaved_runways = models.CharField(max_length=200, blank=True, null=True)
    area = models.CharField(max_length=1000, blank=True, null=True)
    area_comparative = models.CharField(max_length=1700, blank=True, null=True)

    background = models.CharField(max_length=4600, blank=True, null=True)
    birth_rate = models.CharField(max_length=150, blank=True, null=True)
    broadcast_media = models.CharField(max_length=893, blank=True, null=True)
    budget = models.CharField(max_length=250, blank=True, null=True)
    budget_surplus_or_deficit = models.CharField(max_length=650, blank=True, null=True)

    capital = models.CharField(max_length=600, blank=True, null=True)
    carbon_dioxide_emissions_from_consumption_of_energy = models.CharField(max_length=30, blank=True, null=True)
    central_bank_discount_rate = models.CharField(max_length=325, blank=True, null=True)
    children_under_the_age_of_5_years_underweight = models.CharField(max_length=15, blank=True, null=True)
    climate = models.CharField(max_length=850, blank=True, null=True)
    coastline = models.CharField(max_length=1600, blank=True, null=True)
    commercial_bank_prime_lending_rate = models.CharField(max_length=175, blank=True, null=True)
    communications_note = models.CharField(max_length=100, blank=True, null=True)
    constitution = models.CharField(max_length=800, blank=True, null=True)
    country_name = models.CharField(max_length=600, blank=True, null=True)
    crude_oil_exports = models.CharField(max_length=50, blank=True, null=True)
    crude_oil_imports = models.CharField(max_length=50, blank=True, null=True)
    crude_oil_production = models.CharField(max_length=50, blank=True, null=True)
    crude_oil_proved_reserves = models.CharField(max_length=50, blank=True, null=True)
    current_account_balance = models.CharField(max_length=75, blank=True, null=True)

    death_rate = models.CharField(max_length=300, blank=True, null=True)
    debt_external = models.CharField(max_length=325, blank=True, null=True)
    demographic_profile = models.CharField(max_length=1950, blank=True, null=True)
    dependency_status = models.CharField(max_length=650, blank=True, null=True)
    dependent_areas = models.CharField(max_length=850, blank=True, null=True)
    diplomatic_representation_from_the_us = models.CharField(max_length=500, blank=True, null=True)
    diplomatic_representation_in_the_us = models.CharField(max_length=1200, blank=True, null=True)
    disputes_international = models.CharField(max_length=3500, blank=True, null=True)
    distribution_of_family_income_gini_index = models.CharField(max_length=100, blank=True, null=True)
    drinking_water_source = models.CharField(max_length=275, blank=True, null=True)

    economy_overview = models.CharField(max_length=7300, blank=True, null=True)
    education_expenditures = models.CharField(max_length=25, blank=True, null=True)
    electricity_consumption = models.CharField(max_length=50, blank=True, null=True)
    electricity_exports = models.CharField(max_length=50, blank=True, null=True)
    electricity_from_fossil_fuels = models.CharField(max_length=50, blank=True, null=True)
    electricity_from_hydroelectric_plants = models.CharField(max_length=50, blank=True, null=True)
    electricity_from_nuclear_fuels = models.CharField(max_length=50, blank=True, null=True)
    electricity_from_other_renewable_sources = models.CharField(max_length=50, blank=True, null=True)
    electricity_imports = models.CharField(max_length=50, blank=True, null=True)
    electricity_installed_generating_capacity = models.CharField(max_length=75, blank=True, null=True)
    electricity_production = models.CharField(max_length=50, blank=True, null=True)
    elevation_extremes = models.CharField(max_length=650, blank=True, null=True)
    environment_current_issues = models.CharField(max_length=750, blank=True, null=True)
    environment_international_agreements = models.CharField(max_length=850, blank=True, null=True)
    ethnic_groups = models.CharField(max_length=600, blank=True, null=True)
    exchange_rates = models.CharField(max_length=600, blank=True, null=True)
    executive_branch = models.CharField(max_length=3100, blank=True, null=True)
    exports = models.CharField(max_length=250, blank=True, null=True)
    exports_commodities = models.CharField(max_length=500, blank=True, null=True)
    exports_partners = models.CharField(max_length=200, blank=True, null=True)

    fiscal_year = models.CharField(max_length=100, blank=True, null=True)
    flag_description = models.CharField(max_length=1100, blank=True, null=True)
    freshwater_withdrawal_domesticindustrialagricultural = models.CharField(max_length=100, blank=True, null=True)

    gdp_composition_by_sector = models.CharField(max_length=150, blank=True, null=True)
    gdp_official_exchange_rate = models.CharField(max_length=475, blank=True, null=True)
    gdp_per_capita_ppp = models.CharField(max_length=425, blank=True, null=True)
    gdp_purchasing_power_parity = models.CharField(max_length=600, blank=True, null=True)
    gdp_real_growth_rate = models.CharField(max_length=150, blank=True, null=True)
    geographic_coordinates = models.CharField(max_length=525, blank=True, null=True)
    geography_note = models.CharField(max_length=1000, blank=True, null=True)
    government_note = models.CharField(max_length=350, blank=True, null=True)
    government_type = models.CharField(max_length=4400, blank=True, null=True)

    health_expenditures = models.CharField(max_length=25, blank=True, null=True)
    heliports = models.CharField(max_length=200, blank=True, null=True)
    hivaids_adult_prevalence_rate = models.CharField(max_length=75, blank=True, null=True)
    hivaids_deaths = models.CharField(max_length=75, blank=True, null=True)
    hivaids_people_living_with_hivaids = models.CharField(max_length=75, blank=True, null=True)
    hospital_bed_density = models.CharField(max_length=50, blank=True, null=True)
    household_income_or_consumption_by_percentage_share = models.CharField(max_length=150, blank=True, null=True)

    illicit_drugs = models.CharField(max_length=1300, blank=True, null=True)
    imports = models.CharField(max_length=250, blank=True, null=True)
    imports_commodities = models.CharField(max_length=300, blank=True, null=True)
    imports_partners = models.CharField(max_length=150, blank=True, null=True)
    independence = models.CharField(max_length=800, blank=True, null=True)
    industrial_production_growth_rate = models.CharField(max_length=75, blank=True, null=True)
    industries = models.CharField(max_length=600, blank=True, null=True)
    infant_mortality_rate = models.CharField(max_length=400, blank=True, null=True)
    inflation_rate_consumer_prices = models.CharField(max_length=600, blank=True, null=True)
    international_law_organization_participation = models.CharField(max_length=650, blank=True, null=True)
    international_organization_participation = models.CharField(max_length=800, blank=True, null=True)
    internet_country_code = models.CharField(max_length=150, blank=True, null=True)
    internet_hosts = models.CharField(max_length=175, blank=True, null=True)
    internet_users = models.CharField(max_length=400, blank=True, null=True)
    investment_gross_fixed = models.CharField(max_length=75, blank=True, null=True)
    irrigated_land = models.CharField(max_length=200, blank=True, null=True)

    judicial_branch = models.CharField(max_length=1100, blank=True, null=True)

    labor_force = models.CharField(max_length=200, blank=True, null=True)
    labor_force_by_occupation = models.CharField(max_length=450, blank=True, null=True)
    land_boundaries = models.CharField(max_length=800, blank=True, null=True)
    land_use = models.CharField(max_length=650, blank=True, null=True)
    languages = models.CharField(max_length=750, blank=True, null=True)
    legal_system = models.CharField(max_length=2000, blank=True, null=True)
    legislative_branch = models.CharField(max_length=2350, blank=True, null=True)
    life_expectancy_at_birth = models.CharField(max_length=350, blank=True, null=True)
    literacy = models.CharField(max_length=600, blank=True, null=True)
    location = models.CharField(max_length=1100, blank=True, null=True)

    major_cities_population = models.CharField(max_length=200, blank=True, null=True)
    major_infectious_diseases = models.CharField(max_length=700, blank=True, null=True)
    manpower_available_for_military_service = models.CharField(max_length=150, blank=True, null=True)
    manpower_fit_for_military_service = models.CharField(max_length=150, blank=True, null=True)
    manpower_reaching_militarily_significant_age_annually = models.CharField(max_length=60, blank=True, null=True)
    map_references = models.CharField(max_length=250, blank=True, null=True)
    maritime_claims = models.CharField(max_length=525, blank=True, null=True)
    market_value_of_publicly_traded_shares = models.CharField(max_length=150, blank=True, null=True)
    maternal_mortality_rate = models.CharField(max_length=50, blank=True, null=True)
    median_age = models.CharField(max_length=100, blank=True, null=True)
    merchant_marine = models.CharField(max_length=1250, blank=True, null=True)
    military_branches = models.CharField(max_length=600, blank=True, null=True)
    military_expenditures = models.CharField(max_length=150, blank=True, null=True)
    military_note = models.CharField(max_length=1800, blank=True, null=True)
    military_service_age_and_obligation = models.CharField(max_length=750, blank=True, null=True)

    national_anthem = models.CharField(max_length=825, blank=True, null=True)
    national_holiday = models.CharField(max_length=400, blank=True, null=True)
    national_symbols = models.CharField(max_length=200, blank=True, null=True)
    nationality = models.CharField(max_length=200, blank=True, null=True)
    natural_gas_consumption = models.CharField(max_length=40, blank=True, null=True)
    natural_gas_exports = models.CharField(max_length=40, blank=True, null=True)
    natural_gas_imports = models.CharField(max_length=40, blank=True, null=True)
    natural_gas_production = models.CharField(max_length=40, blank=True, null=True)
    natural_gas_proved_reserves = models.CharField(max_length=50, blank=True, null=True)
    natural_hazards = models.CharField(max_length=1500, blank=True, null=True)
    natural_resources = models.CharField(max_length=400, blank=True, null=True)
    net_migration_rate = models.CharField(max_length=325, blank=True, null=True)

    obesity_adult_prevalence_rate = models.CharField(max_length=15, blank=True, null=True)

    people_note = models.CharField(max_length=450, blank=True, null=True)
    physicians_density = models.CharField(max_length=50, blank=True, null=True)
    pipelines = models.CharField(max_length=175, blank=True, null=True)
    political_parties_and_leaders = models.CharField(max_length=2300, blank=True, null=True)
    political_pressure_groups_and_leaders = models.CharField(max_length=1400, blank=True, null=True)
    population = models.CharField(max_length=2500, blank=True, null=True)
    population_below_poverty_line = models.CharField(max_length=250, blank=True, null=True)
    population_growth_rate = models.CharField(max_length=275, blank=True, null=True)
    ports_and_terminals = models.CharField(max_length=600, blank=True, null=True)
    public_debt = models.CharField(max_length=900, blank=True, null=True)

    railways = models.CharField(max_length=325, blank=True, null=True)
    refined_petroleum_products_consumption = models.CharField(max_length=35, blank=True, null=True)
    refined_petroleum_products_exports = models.CharField(max_length=35, blank=True, null=True)
    refined_petroleum_products_imports = models.CharField(max_length=35, blank=True, null=True)
    refined_petroleum_products_production = models.CharField(max_length=35, blank=True, null=True)
    refugees_and_internally_displaced_persons = models.CharField(max_length=700, blank=True, null=True)
    religions = models.CharField(max_length=400, blank=True, null=True)
    reserves_of_foreign_exchange_and_gold = models.CharField(max_length=225, blank=True, null=True)
    roadways = models.CharField(max_length=275, blank=True, null=True)

    sanitation_facility_access = models.CharField(max_length=275, blank=True, null=True)
    school_life_expectancy_primary_to_tertiary_education = models.CharField(max_length=75, blank=True, null=True)
    sex_ratio = models.CharField(max_length=250, blank=True, null=True)
    stock_of_broad_money = models.CharField(max_length=350, blank=True, null=True)
    stock_of_direct_foreign_investment_abroad = models.CharField(max_length=100, blank=True, null=True)
    stock_of_direct_foreign_investment_at_home = models.CharField(max_length=100, blank=True, null=True)
    stock_of_domestic_credit = models.CharField(max_length=225, blank=True, null=True)
    stock_of_narrow_money = models.CharField(max_length=600, blank=True, null=True)
    suffrage = models.CharField(max_length=550, blank=True, null=True)

    taxes_and_other_revenues = models.CharField(max_length=225, blank=True, null=True)
    telephone_system = models.CharField(max_length=1800, blank=True, null=True)
    telephones_main_lines_in_use = models.CharField(max_length=40, blank=True, null=True)
    telephones_mobile_cellular = models.CharField(max_length=50, blank=True, null=True)
    terrain = models.CharField(max_length=925, blank=True, null=True)
    total_fertility_rate = models.CharField(max_length=40, blank=True, null=True)
    total_renewable_water_resources = models.CharField(max_length=45, blank=True, null=True)
    trafficking_in_persons = models.CharField(max_length=2400, blank=True, null=True)
    transportation_note = models.CharField(max_length=1100, blank=True, null=True)

    unemployment_rate = models.CharField(max_length=225, blank=True, null=True)
    unemployment_youth_ages_15_24 = models.CharField(max_length=75, blank=True, null=True)
    urbanization = models.CharField(max_length=500, blank=True, null=True)

    waterways = models.CharField(max_length=1200, blank=True, null=True)
